### ISSUE TITLE
Draw shadows and "penumbra" at different times

### ISSUE THREAD

**Issue by Sungray** [matiasah/shadows#11]
Right now when you draw the lightworld, everything is drawn at once. So if you have a tree, and your character passes next to the tree, if you draw the lightworld last, the character shadow will always be drawn on the tree, which doesn't look good. You can draw the lightworld at a different time (before the objects) so that the shadow will be drawn below them, but then the "penumbra" will also be drawn before the objects, which is not good.

Basically, this is the order I want :
1/ tiles
2/ shadows
3/ items, players, monsters, trees...
4/ black canvas (penumbra)

Right now I have tiles, items, shadows&canvas.

Several solutions are possible :

We could separate the LightWorld:Draw() in 2 methods : LightWorld:DrawShadows() and LightWorld:DrawPenumbra(), so that I can call DrawShadows, then draw my items, then DrawPenumbra.

Could also give every shadow object it's draw method and a flag to avoid drawing it during LightWorld:draw(). We could keep those shadows stored for each object it's attached with, and during drawing, call the object's shadow:draw() manually.

**Comment by matiasah** [comment]
The problem with having draw methods separate, is that when you draw the stuff in different calls, the shadows don't merge.

I'm not exactly sure what you mean by drawing the penumbra, but that effect is only achieved with a radial blur effect. Basically every shadow has it.

**Comment by Sungray** [comment]
By penumbra I meant the final black layer, where the objects are not lit. Should've said "darkness" instead.

But then, the shadows are always drawn above everything else. It's impossible to draw a shadow behind an object, so perspective is not possible right ?

**Comment by matiasah** [comment]
Technically the ambient color aka darkness is the one that causes objects to have shadows. Lights just enlighten this layer.

If you want your trees not to get covered by the players' shadow, you just have to draw the tree image on the DrawSprites callback of the light world.

That method enlightens stuff.

**Comment by Sungray** [comment]
I see, seems good ! Thanks.
