### ISSUE TITLE
Nil xcp when resizing

### ISSUE THREAD

**Issue by Sungray** [matiasah/shadows#12]
LightWorld.lua, line 37, when no stars are created

```
        for Index, Light in pairs(self.Stars) do
            
            Light:Resize(Width, Height)
            
        end
```

should be

```
    if(self.Stars) then
        for Index, Light in pairs(self.Stars) do
            
            Light:Resize(Width, Height)
            
        end
    end
```

**Comment by matiasah** [comment]
Did you mean
```lua
if next(self.Stars) then
```
The condition you mentioned there only checks that the table self.Stars exists, which is always is true because it's initialized in the constructor.

**Comment by matiasah** [comment]
Unless you're calling directly
```lua
LightWorld:Resize(w, h)
```
(Instead of calling newLightWorld:Resize)
```lua
local LightWorld = require("shadows.LightWorld")
local newLightWorld = LightWorld:new()

newLightWorld:Resize(w, h)
```
Which is a common mistake that I often do.

**Comment by Sungray** [comment]
Yess, my mistake, you're exactly right, was calling LightWorld. Thanks !
