### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Rolice** [matiasah/shadows#2]
Hello,
I am not so experienced with LÖVE engine, especially at the part with libraries. I cannot find information about library usage. Only thing I found is about a `lib/` folder that is being expected under Linux, but nothing is said about Windows or OSX/macOS.

I have tried various ways to include and require the library but with no success.

Now, entering on your Wiki here, in GitHub, I still see no section about installation of the library. This would definitely prevent significant amount of users from installing the library, in my opinion.

**Comment by Rolice** [comment]
I have found my mistake in the call of a method. However, such instructions section is a nice to have feature of the repo.

**Comment by matiasah** [comment]
My apologies, what was your mistake so I could add that to the wiki?
I have added a simple installation instructions on it, I'm afraid I haven't tested it on Linux because I don't have Linux and my machine isn't powerful enough to stand using a virtual machine.

**Comment by Rolice** [comment]
Great, thanks. I think  this section will guide a user very easily what one have to do to install the library in their application. Additionally, as far as I read packaging of Love games libraries should be placed in `lib/` folder of the project for Linux. I made it the same way under macOS, currently. I hope this information might help.
