### ISSUE TITLE
Does it work on mobile

### ISSUE THREAD

**Issue by zerodarkzone** [matiasah/shadows#21]
Hi,
Have anyone tried to run this on android to see how it performs?

**Comment by matiasah** [comment]
It does work on android, however it was developed to work on computers so it's probably not going to perform well if you want it to be on a dynamic environment. (It heavily relies on canvases, canvas switches are expensive on mobile platforms).

But yes, the shaders were implemented to be compatible with OpenGL ES.

**Comment by Skeletonxf** [comment]
I test periodically on mobile and the shader code should be 100% compatible if it's changed very little for a few months. Having decent performance while on mobile is going to be the harder thing. If you move a lot of bodies and lights around every frame your performance is not likely to be very good.
