### ISSUE TITLE
Body:SetPhysics is nil

### ISSUE THREAD

**Issue by Skeletonxf** [matiasah/shadows#23]
I believe the documentation https://github.com/matiasah/shadows/wiki/Body may need updating to reflect doing
```lua
body:GetTransform():SetParent(lightWorld:TrackBody(physicsBody))
```
instead

**Comment by matiasah** [comment]
Would Body:TrackPhysics work?

I forgot to update the documentation about Body:SetPhysics.

**Comment by Skeletonxf** [comment]
Apologies I incorrectly transposed the code for getting Lights to sync with physics bodies to Bodies syncing with physics bodies.
 
```lua
Body:InitFromPhysics(physicsBody)
```
works fine, as does
```
light:GetTransform():SetParent(lightWorld:TrackBody(physicsBody))
```

I couldn't get Body:TrackPhysics to also work with shadows attempting the initialization manually.

```lua
local body = Body:new(lightWorld)
PolygonShadow:new(body, physicsBody:getPoints())
```
creates shadows on screen but unsurprisingly they don't track anything

```lua
local body = Body:new(lightWorld)::TrackPhysics(physicsBody)
PolygonShadow:new(body, physicsBody:getPoints())
```
does not seem to render any shadows?

Body:InitFromPhysics does not appear to be documented on the wiki for Body either

**Comment by matiasah** [comment]
Out of curiosity, you weren't using ::TrackPhysics with the double colon character, right?

**Comment by matiasah** [comment]
On the other hand, physicsBody:getPoints() shouldn't be possible, you should be obtaining polygon points from polygon shapes obtained from the fixtures.

**Comment by Skeletonxf** [comment]
I was not using double colons, that was an error in transposing the code and its variable names. I am using https://github.com/SSYGEN/windfield which creates a collider with methods of of a single body, fixture and shape composed together.

It may help if I attach the love file (github does not allow .love files but the zip is valid to convert to .love and play). The shaders code is in graphics/shaders.lua on lines 34 to 37

[bullets.zip](https://github.com/matiasah/shadows/files/1804735/bullets.zip)

**Comment by matiasah** [comment]
I'm guessing
```lua
local body = Body:new(world):TrackPhysics(object)
PolygonShadow:new(body, object:getPoints())
```
Body:new(world) is correct, but Body:TrackPhysics(object) shouldn't return anything. If you print the value of 'body', it should be 'nil'. That's why when you were trying to do PolygonShadow:new(body, ....) it didn't work, you're trying to create a polygon shadow on a nil value.

**Comment by matiasah** [comment]
But, I'm uncertain of something. You're trying to make a light, track a body?

**Comment by Skeletonxf** [comment]
That seems to be the source of the problem. I had assumed it would return the body back.

```lua
local body = Body:new(world)
body:TrackPhysics(object)
PolygonShadow:new(body, object:getPoints())
```
works

I am indeed trying to make the light track a body. The body is the player (or at least would be as I extend the template), and I want the player to shine light from its current location, which is defined by the body.

Lights attached to bodies has always worked since I've been using the library, though perhaps it was not intended?

**Comment by matiasah** [comment]
The way you were using it:
```lua
body:GetTransform():SetParent(lightWorld:TrackBody(physicsBody))
```
Is correct and was intended to be used that way, however I could figure out a way to do so more cleanly. The major problem with this approach is that body trackers are only garbage collected once a body is destroyed, which I'm not sure if it always happens.

**Comment by Skeletonxf** [comment]
perhaps?

```lua
light:TrackBody(physicsBody)
```

Do you mean that if a body tracker stops being used it isn't garbage collected till the body it was tracking is?

**Comment by matiasah** [comment]
The body transform releases itself once the body it was tracking has been destroyed.
https://github.com/matiasah/shadows/blob/master/BodyTransform.lua#L37

**Comment by Skeletonxf** [comment]
That seems quite reasonable. I presume if it needs to be released beforehand then the code using it could manually call `bodyTransform:Remove()`?

**Comment by matiasah** [comment]
Yeah, you can do that too. However, I could also use a weak table to eliminate unreferenced body trackers.

**Comment by Skeletonxf** [comment]
Regardless I think the undocumented methods on the wiki are resolved now
