### ISSUE TITLE
Get Light Vectors on Bodies

### ISSUE THREAD

**Issue by ghost** [matiasah/shadows#25]
Hey @matiasah - Perhaps this is a silly question, so sorry in advance. :)

I'm curious about using this library to implement lighting conditions in a plant-growth simulation. So the idea is, plants should grow toward light, and they should cast shade on their lower leaves and smaller plants.

Is it possible to use `shadows`, as it is now, to calculate the light intensity at a particular point, or upon an object? And, the direction of that light?

**Comment by matiasah** [comment]
Calculating per point is probably going to be too expensive, I'm currently calculating the shadow of every shape and then merging all into a single image. It might be better if you get the color of the pixel at that position, or do you need it to work also with the off-screen elements? (What's not visible in the screen)
![imagen](https://user-images.githubusercontent.com/5008893/39153557-d7dace5e-4721-11e8-9804-7b16af9b2e98.png)

**Comment by ghost** [comment]
That's an interesting question: I'm not yet familiar with how shaders work, but now I'm wondering if they happen purely at the display level.. E.g., can the application even "know" what things outside the view port look like?

To answer your questions: yes, querying a sparse matrix of points for their colour and brightness would be an acceptable proxy in my case. Though, the vector would be missing, which is a shame.

And: yes, I'd like to have things outside the view window also calculate this.

I'm thinking using a full lighting engine to achieve all this is probably too heavyweight. I'm totally fine with taking absurd shortcuts for this if I go ahead with it. I was just wondering if this engine happened to have a low-cost API to do this without much computational overhead, like as a side-effect of how light and shadow are already calculated. I think the answer is no? :)

On 23 April 2018 22:06:09 GMT+01:00, "Matías Hermosilla" <notifications@github.com> wrote:
>Calculating per point is probably going to be too expensive, I'm
>currently calculating the shadow of every shape and then merging all
>into a single image. It might be better if you get the color of the
>pixel at that position, or do you need it to work also with the
>off-screen elements? (What's not visible in the screen)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matiasah/shadows/issues/25#issuecomment-383722977

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matiasah** [comment]
Well, per-light, there's a image cache that can be used to get this value you want. As per-star, it's much different because stars are made to be put in far distances so they only display a area the size of the screen.

I could add a method that returns the color of the lights in a specific point (x,y), but it will only work for lights and not for stars.

**Comment by ghost** [comment]
No, the idea isn't to calculate something on the lights, but rather on the objects the light hits or casts shadows from. If the information isn't already there as a side-effect, I think it's unlikely that it could be calculated efficiently. Probably, it would be valuable for some applications! But my idea would involve a lot of calls to calculate light vectors across a wide field on many objects. I think shadows isn't built for this. :)

On 23 April 2018 23:06:00 GMT+01:00, "Matías Hermosilla" <notifications@github.com> wrote:
>Well, per-light, there's a image cache that can be used to get this
>value you want. As per-star, it's much different because stars are made
>to be put in far distances so they only display a area the size of the
>screen.
>
>I could add a method that returns the color of the lights in a specific
>point (x,y), but it will only work for lights and not for stars.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matiasah/shadows/issues/25#issuecomment-383738187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
