### ISSUE TITLE
Scaling is broken

### ISSUE THREAD

**Issue by Quozul** [matiasah/shadows#28]
At the scale of 1, everything is normal
![image](https://user-images.githubusercontent.com/30729291/44619247-a65b8d00-a883-11e8-92f1-a1569bb25525.png)
But when scaling up or down, the shadows are not in the right place
![image](https://user-images.githubusercontent.com/30729291/44619251-bc694d80-a883-11e8-81f7-11e5b902de44.png)

**Comment by matiasah** [comment]
Is this the DEMO.love? I might have forgotten updating this, I'm going to check it out.

**Comment by matiasah** [comment]
I commited 394ba90 but heightmap still seems to be broken, I'm going to try to fix that.

**Comment by matiasah** [comment]
The demos seem to be fixed, could you try them again?

**Comment by Quozul** [comment]
Just tested the demos, they're fixed, thanks for the fast reply!
