### ISSUE TITLE
Standard Demo wiki has typos

### ISSUE THREAD

**Issue by GoogleFrog** [matiasah/shadows#31]
https://github.com/matiasah/shadows/wiki/Standard-Demonstration

There are a few typos that prevent the wiki example working out of the box.
 - Line 42: PolygonShape should be PolygonShadow.
 - Line 63: LightWorld should be newLightWorld

**Comment by matiasah** [comment]
Thank you, I agree that PolygonShape should be PolygonShadow, but why should LightWorld be newLightWorld? or where?

**Comment by matiasah** [comment]
Okay I just figured out, thanks for the correction!
