### ISSUE TITLE
Big map - too big for canvas

### ISSUE THREAD

**Issue by Sungray** [matiasah/shadows#7]
Hi,

I have a huge map, too big for the canvases, but I'm only displaying small part of it at a given time. So I want the lightworld canvas to be drawn only from a point relatively close to the camera, not over all the map, with a size determined by the maximum zoom level, and the ability to move the canvas along with the camera.

**Comment by Skeletonxf** [comment]
A slightly hackish way I've managed to overcome this is having a map sized only to cover the window and then syncing up all the relevant entities in the larger game world to the positions on the canvas for shading. Obviously it's not an ideal solution and creates a lot of work but it does solve the performance issue.

**Comment by matiasah** [comment]
I don't think I'm understanding correctly, could you describe your problem with a couple of screenshots?
Is it the LightWorld:SetPosition method of the LightWorld?
https://github.com/matiasah/shadows/wiki/LightWorld

**Comment by Sungray** [comment]
Hmm maybe I'm using it wrong. And maybe the new "zoom" implementation could fix my problem. But basically, I'm getting this :
![image](https://cloud.githubusercontent.com/assets/3531871/26530014/3a73b2dc-43cd-11e7-871a-db2c626298f4.png)

By modifying LightWorld.lua :

```
function LightWorld:new(w,h)
	
	local World = setmetatable({}, LightWorld)
	--local Width, Height = love.graphics.getDimensions()
	local Width, Height = w,h
```
I needed to modify this because the window dimension is too small. I need to be able to zoom out and move around in a huge map.

I'm using the Gamera library in case you know about it.

I'm not using physics.

**Comment by matiasah** [comment]
I get you, but the LightWorld's Canvas is supposed to be a kind of 'hud', so it's the size of the graphics screen and it paints on it only what needs to be visible.
Could you try how it works with the LightWorld:SetPosition implementation? You can also try the demo if you want to see the usage.

**Comment by Sungray** [comment]
Thanks, I see what you mean. How do you deal with a window resize ?

**Comment by matiasah** [comment]
I haven't thought of that, does your game require of a window resizing feature? If so, I can implement a callback on the library.

**Comment by Sungray** [comment]
Yes, I want to keep the ability to switch from windowed to fullscreen and resizing. That would be awesome.

**Comment by Skeletonxf** [comment]
My game does as well. I've been just creating a new world at the new size and refilling it to handle resizes currently.

**Comment by matiasah** [comment]
I just implemented a LightWorld:Resize(w, h) method you could use, it doesn't have any complexity than just creating a new canvas and setting the light world to paint everything on it.

**Comment by Sungray** [comment]
Great, thank you very much, appreciate it !
